name: daily_nest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.2
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.4
  firebase_auth: ^5.5.1
  font_awesome_flutter: ^10.7.0
  syncfusion_flutter_charts: ^20.4.48  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/icons8-login-50.png
    - assets/images/icons8-easter-eggs-100.png